name: Publish
on:
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    steps:
    - uses: actions/checkout@v3
    - name: Set Taged Image Name
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: |
        export IMAGE_VERSION="${GITHUB_REF#refs/tags/}"
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
        echo "NEED_IMAGE_PUSH=true" >> $GITHUB_ENV
        echo "LATEST_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/kairos-core-opensuse-k3s-custom:latest" >> $GITHUB_ENV
        echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/kairos-core-opensuse-k3s-custom:${IMAGE_VERSION}" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: ${{ env.NEED_IMAGE_PUSH == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: ${{ env.NEED_IMAGE_PUSH == 'true' }}
        tags: |
          ${{ env.LATEST_IMAGE_NAME }}
          ${{ env.IMAGE_NAME }}
